.include "../../maintainer.mk"

PLUGIN_NAME=		if-pppoe
PLUGIN_VERSION=		0.5
PLUGIN_COMMENT=		Kernel-mode PPPoE (in-kernel driver replacing mpd5, reboot to apply)
PLUGIN_DEPENDS=		if-pppoe-kmod
PLUGIN_MAINTAINER=	${MAINTAINER}
PLUGIN_WWW=		https://github.com/nashant/if_pppoe

.include "../../Mk/plugins.mk"
