"""ctl-contract: replays the engine-vs-real-pppoectl contract fixtures
(plugin/net/if-pppoe/tests/fixtures/ctl-contract/, generated by
gen_ctl_contract.php from the real lib/Pppoectl.php + lib/Engine.php argv
shapes -- see tests/engine/test_ctl_contract.php for the offline half of
this same contract, which replays them against the recording PHP stub
instead) against the real sbin/pppoectl on the lab client. This is the
test the "-S -f /dev/stdin" bug in 0.2 needed and never had: only the
stub was ever exercised.

Replay only creates a clone, runs discovery + settings + mtu + a
list-mode read-back, then destroys it (ctl-contract-replay.sh) -- no
PPPoE server is dialed, so this needs no `server` fixture, just `driver`,
exactly like test_pppoectl_ctl_live.py.
"""
from __future__ import annotations

import pytest

from lab import push_ctl_contract

pytestmark = pytest.mark.datapath

CTL_CONTRACT_DEVICE = "pppoe9"
CTL_CONTRACT_PARENT = "vtnet1"


def test_ctl_contract_replays_against_the_real_pppoectl(driver):
    fixtures_dir, replay_script = push_ctl_contract(driver)
    cmd = f"sh {replay_script} {fixtures_dir} {CTL_CONTRACT_PARENT} {CTL_CONTRACT_DEVICE}"
    r = driver.run(cmd, root=True, timeout=90)
    assert r.returncode == 0 and "FAIL" not in r.stdout, (
        f"ctl-contract-replay.sh failed (rc={r.returncode}):\n{r.stdout}\n{r.stderr}"
    )
