#!/bin/sh
# ctl-contract-replay.sh <fixtures-dir> <parent-if> <device> [pppoectl-path] [ifconfig-path]
#
# Replays the ctl-contract fixtures (tests/fixtures/ctl-contract/<name>/,
# generated by gen_ctl_contract.php from ctl_contract_fixtures.php: one
# argv token per line in argv.{discovery,settings,mtu,verify}, raw bytes in
# settings.conf and stdin, POSIX `KEY='value'` lines in expect -- no JSON
# parser needed here) against the real sbin/pppoectl. Must run as root on
# FreeBSD with if_pppoe.ko loaded; does not dial (create/configure/destroy
# only), so it needs no PPPoE server. Used by tests/functional/
# test_ctl_contract.py (lab) and .github/scripts/smoke-guest.sh (CI).
set -eu

FIXTURES=${1:?usage: ctl-contract-replay.sh fixtures-dir parent-if device [pppoectl-path] [ifconfig-path]}
PARENT=${2:?}
DEV=${3:?}
POCTL=${4:-/usr/local/sbin/pppoectl}
IFCONFIG=${5:-ifconfig}
FAILED=0

log() { echo "ctl-contract-replay: $*"; }
note_fail() { echo "ctl-contract-replay: FAIL: $*" >&2; FAILED=1; }

# Runs the argv file $1 as a command: one line = one argv element, so a
# token with spaces/tabs is never re-split. @PARENT@/@DEV@/@CFGFILE@/@POCTL@/
# @IFCONFIG@ are substituted whole (never as a substring) so a service-name
# or ac-name fixture value that happened to equal one of those strings could
# not be confused with the placeholder -- none of the fixtures' own values
# do. argv[0] in every generated fixture is @POCTL@ or @IFCONFIG@, never a
# hardcoded path: CI runs its own freshly built pppoectl, not whatever (or
# nothing) lives at /usr/local/sbin/pppoectl in the guest.
run_argv_file() {
	_argv_file=$1
	set --
	while IFS= read -r tok; do
		case "$tok" in
		'@PARENT@') tok=$PARENT ;;
		'@DEV@') tok=$DEV ;;
		'@CFGFILE@') tok=$CFGFILE ;;
		'@POCTL@') tok=$POCTL ;;
		'@IFCONFIG@') tok=$IFCONFIG ;;
		esac
		set -- "$@" "$tok"
	done < "$_argv_file"
	"$@"
}

check() { # description substring; a plain substring match, not line-anchored like
	# Pppoectl::verify()'s regexes -- close enough for these fixtures' values
	case "$out" in
	*"$2"*) ;;
	*) note_fail "$name: expected to see: $2" ;;
	esac
}

run_scenario() {
	dir=$1
	name=$(basename "$dir")
	log "=== $name"

	$IFCONFIG "$DEV" destroy >/dev/null 2>&1 || true
	if ! $IFCONFIG "$DEV" create; then
		note_fail "$name: ifconfig $DEV create"
		return
	fi
	$IFCONFIG "$DEV" down >/dev/null 2>&1 || true

	if ! run_argv_file "$dir/argv.discovery"; then
		note_fail "$name: discovery ($POCTL -e ...) failed"
		$IFCONFIG "$DEV" destroy >/dev/null 2>&1 || true
		return
	fi

	CFGFILE=$(mktemp "${TMPDIR:-/tmp}/ctl-contract.XXXXXX")
	cp "$dir/settings.conf" "$CFGFILE"
	chmod 600 "$CFGFILE"
	stdin_file=$dir/stdin
	[ -f "$stdin_file" ] || stdin_file=/dev/null
	if ! run_argv_file "$dir/argv.settings" < "$stdin_file"; then
		note_fail "$name: settings (-S -f) failed"
		rm -f "$CFGFILE"
		$IFCONFIG "$DEV" destroy >/dev/null 2>&1 || true
		return
	fi
	rm -f "$CFGFILE"

	# Engine::bringUp runs the read-back (verify) BEFORE the mtu ifconfig call
	# (Engine.php:223-232): replayed in that order, not argv.mtu then argv.verify.
	if ! out=$(run_argv_file "$dir/argv.verify"); then
		note_fail "$name: read-back ($POCTL $DEV) failed"
		$IFCONFIG "$DEV" destroy >/dev/null 2>&1 || true
		return
	fi

	if ! run_argv_file "$dir/argv.mtu"; then
		note_fail "$name: mtu failed"
	fi

	myauthproto='' myauthname='' max_auth_failure='' ipcp='' ipv6cp='' mssfix='' hisauthproto_absent=''
	# shellcheck disable=SC1090 # $dir/expect overwrites the vars declared just above
	. "$dir/expect"
	check myauthproto "myauthproto=${myauthproto} myauthname=\"${myauthname}\""
	if [ "${hisauthproto_absent:-1}" = 1 ]; then
		case "$out" in
		*'hisauthproto='*) note_fail "$name: expected NOT to see: hisauthproto=" ;;
		esac
	fi
	check max-auth-failure "max-auth-failure = ${max_auth_failure}"
	check ipcp "ipcp: $([ "${ipcp}" = 1 ] && echo enable || echo disable)"
	check ipv6cp "ipv6cp: $([ "${ipv6cp}" = 1 ] && echo enable || echo disable)"
	check mssfix "mssfix: $([ "${mssfix}" = 1 ] && echo enable || echo disable)"

	$IFCONFIG "$DEV" destroy >/dev/null 2>&1 || true
}

[ -d "$FIXTURES" ] || { echo "ctl-contract-replay: no such fixtures dir: $FIXTURES" >&2; exit 1; }
count=0
for dir in "$FIXTURES"/*/; do
	[ -d "$dir" ] || continue
	run_scenario "${dir%/}"
	count=$((count + 1))
done
[ "$count" -gt 0 ] || { echo "ctl-contract-replay: no scenarios found under $FIXTURES" >&2; exit 1; }

if [ "$FAILED" != 0 ]; then
	echo "ctl-contract-replay: one or more of $count scenario(s) FAILED" >&2
	exit 1
fi
log "$count scenario(s) passed"
