#!/usr/bin/env python3
"""make-dut-seed.py -- render dut-config.xml.tmpl into the `dut` VM's seed
config.xml and write it to STDOUT, for provision-dut.sh to pipe straight
into a tmpfs dir on the lab host (where genisoimage packs it into the seed
ISO; run.sh already runs genisoimage there for cloud-init cidata disks).

Nothing is generated, stored or persisted here. The credentials are per-run
values that the orchestrating process (plugin-roundtrip.sh) generated and
holds only in memory / its children's environment:

  DUT_API_KEY        API key (sent as-is; OPNsense stores it in clear)
  DUT_API_SECRET     API secret (RAW; only its hash goes into config.xml)
  DUT_PPPOE_PASSWORD PPPoE account password (OPNsense stores <ppp><password>
                     base64-encoded, so the rendered config.xml -- and thus
                     the seed ISO -- carries it; that is why the ISO only
                     ever lives on tmpfs and is shredded once consumed)

Secrets are never accepted on argv (visible to any other local user via
`ps`). The rendered config.xml goes to stdout only, which must be a pipe or
file, never a terminal. There is no secrets file and no work dir.

Root has NO password: <password>*</password>. Access is only by the
ephemeral ssh public key passed as --pubkey-file (its private key lives on
tmpfs for one run, see plugin-roundtrip.sh). Why '*' and not empty, verified
against opnsense/core 25.7.11 src/etc/inc/auth.inc local_user_set():
  - an EMPTY <password> makes local_user_set() log "password is missing" and
    return without creating the user -- root's authorized_keys would then
    never be written, locking out ssh too;
  - the value handed to `pw` is '*' anyway unless $force_password, and '*'
    is not a crypt(3) hash, so password_verify() (web/API login) and
    master.passwd (console/ssh password login) can never match it.

API secret hashing: ApiKeyField::add() (Auth/FieldTypes/ApiKeyField.php)
stores crypt($secret, '$6$') -- glibc SHA-512-crypt. `openssl passwd -6`
writes the identical format. The secret is piped to openssl on STDIN
(`-stdin`), never argv. The RAW secret (not the hash) is what the API client
sends as HTTP Basic auth alongside the key.
"""
from __future__ import annotations

import argparse
import base64
import os
import re
import secrets
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

SECRET_ENV = ("DUT_API_KEY", "DUT_API_SECRET", "DUT_PPPOE_PASSWORD")


def sha512_crypt(secret: str, salt: str) -> str:
    # The secret goes on stdin, never argv -- argv is visible to any other
    # local user via `ps`.
    out = subprocess.run(
        ["openssl", "passwd", "-6", "-salt", salt, "-stdin"],
        input=secret, capture_output=True, text=True, check=True,
    ).stdout.strip()
    if not out.startswith("$6$"):
        raise RuntimeError("unexpected openssl passwd output shape (not $6$...)")
    return out


def render(template: str, values: dict) -> str:
    out = template
    for k, v in values.items():
        out = out.replace(f"@{k}@", v)
    # cheap leftover-placeholder guard: a bare "@FOO@" left in the output
    # means make-dut-seed.py and dut-config.xml.tmpl have drifted apart.
    leftover = re.findall(r"@[A-Z_0-9]+@", out)
    if leftover:
        raise RuntimeError(f"unfilled placeholders in rendered config.xml: {sorted(set(leftover))}")
    return out


def read_env(environ=os.environ) -> dict:
    missing = [k for k in SECRET_ENV if not environ.get(k)]
    if missing:
        raise SystemExit(
            f"make-dut-seed.py: missing env {', '.join(missing)} -- these are per-run values "
            "generated by plugin-roundtrip.sh; never pass them on argv"
        )
    return {k: environ[k] for k in SECRET_ENV}


def build_values(creds: dict, pubkey_line: str, pppoe_username: str, pppoe_service_name: str) -> dict:
    if not pubkey_line.startswith(("ssh-ed25519 ", "ssh-rsa ", "ecdsa-sha2-")):
        raise SystemExit("make-dut-seed.py: --pubkey-file does not look like an ssh public key")
    return {
        "API_KEY": creds["DUT_API_KEY"],
        "API_SECRET_HASH": sha512_crypt(creds["DUT_API_SECRET"], secrets.token_hex(8)),
        "ROOT_AUTHORIZED_KEYS_B64": base64.b64encode((pubkey_line + "\n").encode()).decode(),
        "PPPOE_USERNAME": pppoe_username,
        "PPPOE_PASSWORD_B64": base64.b64encode(creds["DUT_PPPOE_PASSWORD"].encode()).decode(),
        "PPPOE_SERVICE_NAME": pppoe_service_name,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--template", default=str(HERE / "dut-config.xml.tmpl"))
    ap.add_argument("--pubkey-file", required=True,
                    help="the run's EPHEMERAL ssh public key (plugin-roundtrip.sh's tmpfs dir), "
                         "seeded as root's only authorized_keys entry")
    ap.add_argument("--pppoe-username", default="plugintest")
    ap.add_argument("--pppoe-service-name", default="lab",
                    help="must be a service the lab accel-ppp answers: its [pppoe] "
                         "service-name=lab (lab/isp-netns/accel-ppp.conf)")
    args = ap.parse_args()

    if sys.stdout.isatty():
        raise SystemExit("make-dut-seed.py: stdout is a terminal; pipe it (the output embeds the PPPoE password)")

    creds = read_env()
    pubkey_line = Path(args.pubkey_file).read_text().strip()
    values = build_values(creds, pubkey_line, args.pppoe_username, args.pppoe_service_name)
    sys.stdout.write(render(Path(args.template).read_text(), values))
    sys.stdout.flush()
    return 0


if __name__ == "__main__":
    sys.exit(main())
